import './globals.css'
import { Inter } from 'next/font/google'
import { Auth0Provider } from "auth0-spa-js";

// import Login from './login/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pormordo ToDo App',
  description: 'Generated by Hemanth Chowdary',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Auth0Provider
          domain="dev-hemanthchowdary.us.auth0.com"
          clientID="V2Vw3iF1Qr4mdm4PdYGYLvMTCOEy2J6W"
          audience="Yd2oQ9kSpUgZvc8kYwjlob5ZHAdI3okAsUmwjcrr7FLayiTp-tmbQu8VykxLKGU0" 
          authorizationParams={{
            redirect_uri: window.location.origin
          }}      
        >
        {children}
        </Auth0Provider>
          {/* <Login /> */}
      </body>
    </html>
  )
}
